include_recipe 'user/dotfiles/default.rb'
include_recipe 'user/fish/default.rb'
#include_recipe 'user/frgm/default.rb'
include_recipe 'user/github_cli/default.rb'
include_recipe 'user/mise/default.rb'
include_recipe 'user/ssh/default.rb'
include_recipe 'user/claude_code/default.rb'
