include_recipe 'cookbooks/dotfiles/default.rb'
include_recipe 'cookbooks/fish/default.rb'
include_recipe 'cookbooks/asdf/default.rb'
include_recipe 'cookbooks/nvim/default.rb'
include_recipe 'cookbooks/ssh/default.rb'
